[package]
description = "A library for building REST clients"
repository = "https://github.com/SimonPersson/ease"
documentation = "http://simonpersson.github.io/ease/ease/index.html"
name = "ease"
version = "0.4.0"
authors = ["Simon Persson <simon@flaskpost.org>"]
keywords = ["rest", "api", "client", "web"]
license = "MIT"
build = "src/build.rs"

[dependencies]
hyper = "*"
url = "*"
serde = "*"
serde_json = "*"

[build-dependencies]
serde_codegen = "*"
syntex = "*"

[[ example ]]
name = "json"
path = "examples/json/json.rs"

[[ example ]]
name = "strings"
path = "examples/strings.rs"
