[package]
description = "A library for building REST clients"
repository = "https://github.com/SimonPersson/ease"
documentation = "http://simonpersson.github.io/ease/ease/index.html"
name = "ease"
version = "0.1.0"
authors = ["Simon Persson <simon@flaskpost.org>"]
keywords = ["rest", "api", "client", "web"]
license = "MIT"

[dependencies]
hyper = "*"
url = "*"
serde = "*"
serde_macros = "*"

[features]
nightly = []
